"""update Columns

Revision ID: d1427e73e5e6
Revises: 70b47ddbdba6
Create Date: 2020-02-23 13:36:37.477682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1427e73e5e6'
down_revision = '70b47ddbdba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('past_shows', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=540), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talen', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('upcoming_shows', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'upcoming_shows')
    op.drop_column('Venue', 'seeking_talen')
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'past_shows')
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
